runtime: python312
entrypoint: gunicorn --bind 0.0.0.0:$PORT --workers 2 --timeout 60 happypaws.wsgi:application

env_variables:
  DEBUG: "False"
  DJANGO_ALLOWED_HOSTS: ".appspot.com,.run.app"

beta_settings:
  cloud_sql_instances: "happypawschl:southamerica-west1:happypaws"
