# Generated by Django 5.2.14 on 2026-05-30 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('especie', models.CharField(choices=[('canino', 'Canino'), ('felino', 'Felino'), ('ave', 'Ave'), ('reptil', 'Reptil'), ('roedor', 'Roedor'), ('otro', 'Otro')], max_length=20)),
                ('raza', models.CharField(blank=True, max_length=100)),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('F', 'Hembra')], max_length=1)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('color', models.CharField(blank=True, max_length=100)),
                ('microchip', models.CharField(blank=True, max_length=20)),
                ('alergias', models.CharField(blank=True, max_length=500)),
                ('observaciones', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('seguimiento', 'Seguimiento'), ('urgente', 'Urgente'), ('inactivo', 'Inactivo')], default='activo', max_length=20)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('rut', models.CharField(blank=True, max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.CharField(blank=True, max_length=300)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('contacto_emergencia', models.CharField(blank=True, max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'tutores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'veterinarios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Patologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha_diagnostico', models.DateField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('cronica', 'Crónica'), ('aguda', 'Aguda'), ('alerta', 'Alerta')], max_length=20)),
                ('tratamiento_actual', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patologias', to='clinica.paciente')),
            ],
            options={
                'verbose_name_plural': 'patologías',
                'ordering': ['-fecha_diagnostico'],
            },
        ),
        migrations.AddField(
            model_name='paciente',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pacientes', to='clinica.tutor'),
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha_aplicacion', models.DateField()),
                ('proxima_dosis', models.DateField(blank=True, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacunas', to='clinica.paciente')),
            ],
            options={
                'verbose_name_plural': 'vacunas',
                'ordering': ['-fecha_aplicacion'],
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('motivo', models.CharField(max_length=300)),
                ('peso_visita', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temperatura', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('diagnostico', models.TextField(blank=True)),
                ('tratamiento', models.TextField(blank=True)),
                ('requiere_seguimiento', models.CharField(choices=[('no', 'No'), ('programada', 'Sí — próxima cita programada'), ('urgente', 'Sí — urgente')], default='no', max_length=20)),
                ('fecha_proxima_visita', models.DateField(blank=True, null=True)),
                ('indicaciones_tutor', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_curso', 'En curso'), ('completada', 'Completada')], default='pendiente', max_length=20)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='clinica.paciente')),
                ('veterinario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultas', to='clinica.veterinario')),
            ],
            options={
                'ordering': ['-fecha', '-hora'],
            },
        ),
    ]
